// <!-- Vue.js -->
var lesson = [
    {
        id: 1,
        title: "Maths Course",
        subject: "Maths",
        location: "Russia",
        price: 55,
        spaces: 5,
        image: "images/s1.png", // Update the path to your image
        availableInventory: 10,
    },
    {
        id: 2,
        title: "Drama Course",
        subject: "Drama",
        location: "Spain",
        price: 80,
        spaces: 3,
        image: "images/s2.png", // Update the path to your image
        availableInventory: 10,
    },
    {
        id: 3,
        title: "Accounting Course",
        subject: "Accounting",
        location: "Germany",
        price: 50,
        spaces: 2,
        image: "images/s12.png",
        availableInventory: 10,
    },
    {
        id: 4,
        title: "Journaling Course",
        subject: "Journaling",
        location: "Mexico",
        price: 10,
        spaces: 8,
        image: "images/s11.png",
        availableInventory: 10,
    },
    {
        id: 5,
        title: "Coding Course",
        subject: "Coding",
        location: "London",
        price: 50,
        spaces: 7,
        image: "images/s10.png",
        availableInventory: 10,
    },
    {
        id: 6,
        title: "Baking Course",
        subject: "Baking",
        location: "Turkey",
        price: 45,
        spaces: 3,
        image: "images/s9.png",
        availableInventory: 10,
    },
    {
        id: 7,
        title: "Music Course",
        subject: "Music",
        location: "Azerbaijan",
        price: 70,
        spaces: 2,
        image: "images/s8.png",
        availableInventory: 10,
    },
    {
        id: 8,
        title: "Psychology Course",
        subject: "Psychology",
        location: "Georgia",
        price: 90,
        spaces: 12,
        image: "images/s7.png",
        availableInventory: 10,
    },
    {
        id: 9,
        title: "Business Course",
        subject: "Business",
        location: "Argentina",
        price: 20,
        spaces: 9,
        image: "images/s6.png",
        availableInventory: 10,
    },
    {
        id: 10,
        title: "Art Course",
        subject: "Art",
        location: "Italy",
        price: 50,
        spaces: 6,
        image: "images/s5.png",
        availableInventory: 10,
    },
    {
        id: 11,
        title: "Language Course",
        subject: "Language",
        location: "Greece",
        price: 60,
        spaces: 1,
        image: "images/s4.png",
        availableInventory: 10,
    },
    {
        id: 12,
        title: "English Course",
        subject: "English",
        location: "Finland",
        price: 20,
        spaces: 10,
        image: "images/s3.png",
        availableInventory: 10,
    },
];